/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAutomationRouteImport } from './routes/ai-automation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as CopilotsRouteImport } from './routes/copilots'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as KnowledgeDocumentsRouteImport } from './routes/knowledge-documents'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as DepartmentsIndexRouteImport } from './routes/departments/index'
import { Route as DepartmentsSlugRouteImport } from './routes/departments/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAutomationRoute = AiAutomationRouteImport.update({
  id: '/ai-automation',
  path: '/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotsRoute = CopilotsRouteImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeDocumentsRoute = KnowledgeDocumentsRouteImport.update({
  id: '/knowledge-documents',
  path: '/knowledge-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/brain': typeof BrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-documents': typeof KnowledgeDocumentsRoute
  '/operations': typeof OperationsRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/brain': typeof BrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-documents': typeof KnowledgeDocumentsRoute
  '/operations': typeof OperationsRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-automation': typeof AiAutomationRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/brain': typeof BrainRoute
  '/copilots': typeof CopilotsRoute
  '/documents': typeof DocumentsRoute
  '/governance': typeof GovernanceRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/knowledge-documents': typeof KnowledgeDocumentsRoute
  '/operations': typeof OperationsRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/workflows': typeof WorkflowsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-automation'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/brain'
    | '/copilots'
    | '/documents'
    | '/governance'
    | '/insights'
    | '/integrations'
    | '/knowledge'
    | '/knowledge-documents'
    | '/operations'
    | '/platform'
    | '/reports'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/workflows'
    | '/agents/$agentId'
    | '/departments/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-automation'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/brain'
    | '/copilots'
    | '/documents'
    | '/governance'
    | '/insights'
    | '/integrations'
    | '/knowledge'
    | '/knowledge-documents'
    | '/operations'
    | '/platform'
    | '/reports'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/workflows'
    | '/agents/$agentId'
    | '/departments/$slug'
    | '/agents'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/ai-automation'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/brain'
    | '/copilots'
    | '/documents'
    | '/governance'
    | '/insights'
    | '/integrations'
    | '/knowledge'
    | '/knowledge-documents'
    | '/operations'
    | '/platform'
    | '/reports'
    | '/security'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/workflows'
    | '/agents/$agentId'
    | '/departments/$slug'
    | '/agents/'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAutomationRoute: typeof AiAutomationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationRoute: typeof AutomationRoute
  BrainRoute: typeof BrainRoute
  CopilotsRoute: typeof CopilotsRoute
  DocumentsRoute: typeof DocumentsRoute
  GovernanceRoute: typeof GovernanceRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  KnowledgeDocumentsRoute: typeof KnowledgeDocumentsRoute
  OperationsRoute: typeof OperationsRoute
  PlatformRoute: typeof PlatformRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  WorkflowsRoute: typeof WorkflowsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-automation': {
      id: '/ai-automation'
      path: '/ai-automation'
      fullPath: '/ai-automation'
      preLoaderRoute: typeof AiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilots': {
      id: '/copilots'
      path: '/copilots'
      fullPath: '/copilots'
      preLoaderRoute: typeof CopilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-documents': {
      id: '/knowledge-documents'
      path: '/knowledge-documents'
      fullPath: '/knowledge-documents'
      preLoaderRoute: typeof KnowledgeDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAutomationRoute: AiAutomationRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationRoute: AutomationRoute,
  BrainRoute: BrainRoute,
  CopilotsRoute: CopilotsRoute,
  DocumentsRoute: DocumentsRoute,
  GovernanceRoute: GovernanceRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  KnowledgeDocumentsRoute: KnowledgeDocumentsRoute,
  OperationsRoute: OperationsRoute,
  PlatformRoute: PlatformRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  WorkflowsRoute: WorkflowsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
